M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2025-09-09T19:53:15+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-09T19:53:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X93.215Y-68.81
X93.215Y-74.59
T2
X97.75Y-62.675
X102.25Y-62.675
M30
